export const GET_TODO_REQUEST = "GET_TODO_REQUEST";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_FAILURE = "GET_TODO_FAILURE";
export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO_ITEM = "REMOVE_TODO_ITEM";
export const TOGGLE_TODO_STATUS = "TOGGLE_TODO_STATUS";
